#!/usr/bin/env bash


while getopts "hv" flag; do
    case "${flag}" in
        h)
        echo -e "insomnia -[hv]\nUseful command for keeping a Mac from sleeping when the lid is closed... or in general for that matter.\n -h help command\n -v get version number"
        exit 0
        ;;
        v)
            echo "insomnia v1.0.0"
            exit 0
            ;;
    esac
done

cleanup() {
    sudo pmset -bc disablesleep 0
    exit 1;
}

trap cleanup SIGINT

sudo pmset -bc disablesleep 1

while true; do
    sleep 1
done
